name: ride_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # mockito: ^5.2.0
  get: ^4.6.5
  http: ^0.13.4
  email_validator: ^2.0.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.0
  webview_flutter: ^4.4.2
  mocktail: ^0.3.0
  responsive_framework: ^1.1.1
  uuid: ^3.0.6
  intl: ^0.18.0
  hexcolor: 2.0.6
  qr_flutter: ^4.0.0
  device_info_plus: ^4.0.0
  entry: ^0.0.6
  test: ^1.19.5
  country_codes: ^2.2.0
  device_preview: any
  logger: ^1.1.0
  switcher: ^1.0.0
  flutter_switch: ^0.3.2
  pin_code_fields: ^7.4.0
  firebase_core: ^1.20.0
  mixpanel_analytics: ^2.1.1
  firebase_messaging: ^12.0.1
  flutter_local_notifications: 11.0.1
  get_cli: any
  rich_console: ^1.0.4
  build_runner: ^2.2.1
  mockito: ^5.3.2
  flutter_svg: any
  percent_indicator: ^4.2.2
  change_app_package_name: ^1.1.0
  lottie: ^2.3.2
  firebase_core_platform_interface: 4.5.1
  flutter_dotenv: ^5.1.0
  simple_animations: ^5.0.2
  expansion_tile_card: ^3.0.0
  image_gallery_saver: ^2.0.3
  share_plus: any
  expandable_page_view: ^1.0.17




dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: 0.9.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
#    - assets/images/payment/
#    - assets/images/account_menu/
    - .env

  fonts:
    - family: TTFirsNeueTrial
      fonts:
        - asset: assets/fonts/TTFirsNeueTrialLight.ttf
          weight: 100
        - asset: assets/fonts/TTFirsNeueTrialRegular.ttf
          weight: 300
        - asset: assets/fonts/TTFirsNeueTrialMedium.ttf
          weight: 500
        - asset: assets/fonts/TTFirsNeueTrialDemiBold.ttf
          weight: 900
    - family: SF
      fonts:
        - asset: assets/fonts/SFREGULAR.OTF
          weight: 300
        - asset: assets/fonts/SFMEDIUM.OTF
          weight: 500